version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: clarin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: clarin
      POSTGRES_PASSWORD: clarin_secret_2026
      POSTGRES_DB: clarin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clarin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: clarin-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ../deploy/Dockerfile.backend
    container_name: clarin-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://clarin:clarin_secret_2026@postgres:5432/clarin?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: clarin_jwt_secret_change_in_production_2026
      PORT: 8080
      ENV: development
      MINIO_ENDPOINT: clarin-minio:9000
      MINIO_ACCESS_KEY: clarinadmin
      MINIO_SECRET_KEY: Cl@r1nM1n10#2026Secure
      MINIO_BUCKET: clarin-media
      MINIO_USE_SSL: "false"
      MINIO_PUBLIC_URL: https://media.clarin.naperu.cloud
      KOMMO_SUBDOMAIN: comunicacionesacropolisperuorg
      KOMMO_CLIENT_ID: 3bf63873-fddd-43b7-a6ee-f0fbb5e5c13c
      KOMMO_CLIENT_SECRET: ldiWoIW0E0aqGJnkCxkPpZnsS1XH8zwKl5sOZpIk3SdI0TNb0PwsLf2PIt8AF4l2
      KOMMO_ACCESS_: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjZlYjE4MDY0ZTExOGYzNGEzZmZiYmI4NTBhMDEzNmI5NTE5N2FiZTA3OTRiNzRjOTNlMTQ3YWM0OWYwMWUxY2Y3NjU2ZGI1ODdiY2NkZDRlIn0.eyJhdWQiOiIzYmY2Mzg3My1mZGRkLTQzYjctYTZlZS1mMGZiYjVlNWMxM2MiLCJqdGkiOiI2ZWIxODA2NGUxMThmMzRhM2ZmYmJiODUwYTAxMzZiOTUxOTdhYmUwNzk0Yjc0YzkzZTE0N2FjNDlmMDFlMWNmNzY1NmRiNTg3YmNjZGQ0ZSIsImlhdCI6MTc3MTA3OTUyOSwibmJmIjoxNzcxMDc5NTI5LCJleHAiOjE5MjQ5MDU2MDAsInN1YiI6Ijk5MDMxNTkiLCJncmFudF90eXBlIjoiIiwiYWNjb3VudF9pZCI6MzE1MTkyOTEsImJhc2VfZG9tYWluIjoia29tbW8uY29tIiwidmVyc2lvbiI6Miwic2NvcGVzIjpbImNybSIsImZpbGVzIiwiZmlsZXNfZGVsZXRlIiwibm90aWZpY2F0aW9ucyIsInB1c2hfbm90aWZpY2F0aW9ucyJdLCJoYXNoX3V1aWQiOiJlZTRkZGY5NC01ODhhLTQwZGEtODgyNC1jMDhjY2ZjYzRhMzYiLCJhcGlfZG9tYWluIjoiYXBpLWMua29tbW8uY29tIn0.h-HKR6WiQGVTm5rs_yOGE_Lzyb_U4wB_VajFO64UBb4ON_lntBAJ7xhNvhC7ePMl6l5FWGf4hmSBH4SuDnXia09oMb9cGrShhN8XupzI0bHc2Y-95NcUihm1vv58zGmhGkOyMbPnzNTg2LE4s_xHWJfnGLrRMiMGQ82CVxmuXn_ACKiKsHyFcrpjv0mCYrQyiaT-3b4O9tqgjQYz2jJv4vFxcIHKWz93x4zCFJDE3bRQAa9KeovB1MegU5HQmz3G-ZIugD_CoYiXQ8MVWEuGjiH3sBfFcmeKfNxQ4xSD5JL3CbNREI5H7PwIFPi7fEmx1DI-ncgL-wuM70i0Fx8hcw
      KOMMO_REDIRECT_URI: https://clarin.naperu.cloud/api/kommo/callback
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - whatsapp_sessions:/app/sessions
    networks:
      - default
      - dokploy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../deploy/Dockerfile.frontend
    container_name: clarin-frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
      NEXT_PUBLIC_WS_URL: ws://localhost:8080
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - default
      - dokploy-network

volumes:
  postgres_data:
  redis_data:
  whatsapp_sessions:

networks:
  default:
    name: clarin-network
  dokploy-network:
    external: true
